# Generated by Django 3.2.9 on 2021-12-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuntimeGraphs', '0014_ethdataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCDataset',
            fields=[
                ('Date', models.DateTimeField(primary_key=True, serialize=False)),
                ('Open', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('High', models.FloatField()),
                ('Volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SOLDataset',
            fields=[
                ('Date', models.DateTimeField(primary_key=True, serialize=False)),
                ('Open', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('High', models.FloatField()),
                ('Volume', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='CryptoDataset',
            new_name='BNBDataset',
        ),
        migrations.RenameField(
            model_name='bnbdataset',
            old_name='close',
            new_name='Close',
        ),
        migrations.RenameField(
            model_name='bnbdataset',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='bnbdataset',
            old_name='high',
            new_name='High',
        ),
        migrations.RenameField(
            model_name='bnbdataset',
            old_name='low',
            new_name='Low',
        ),
        migrations.RenameField(
            model_name='bnbdataset',
            old_name='open',
            new_name='Open',
        ),
        migrations.RenameField(
            model_name='bnbdataset',
            old_name='volume',
            new_name='Volume',
        ),
        migrations.RenameField(
            model_name='ethdataset',
            old_name='close',
            new_name='Close',
        ),
        migrations.RenameField(
            model_name='ethdataset',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='ethdataset',
            old_name='high',
            new_name='High',
        ),
        migrations.RenameField(
            model_name='ethdataset',
            old_name='low',
            new_name='Low',
        ),
        migrations.RenameField(
            model_name='ethdataset',
            old_name='open',
            new_name='Open',
        ),
        migrations.RenameField(
            model_name='ethdataset',
            old_name='volume',
            new_name='Volume',
        ),
    ]
