# Generated by Django 3.2.9 on 2021-12-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuntimeGraphs', '0015_auto_20211220_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, verbose_name='user password')),
                ('cash', models.IntegerField(default=0)),
                ('coins', models.FloatField(default=0.0)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images')),
            ],
        ),
    ]
